version: '3.7'

services:

  jupyterlab:
    build: ./jupyterlab
    image: jupyter/datascience-notebook
    container_name: jupyterlab
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - "8888:8888"
    networks:
      - default
  minio:
    restart: always
    image: minio/minio
    container_name: datalake_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - default
    command: server /data --console-address ':9001' --address ':9000'
     
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - minio_data:/data

  mlflow-db:
    restart: always
    image: mysql/mysql-server@sha256:fcbe88694872e88ae406bc69540211505eae922a182690d85be6af1a48e5ca0a
    container_name: mlflow_db
    ports:
      - "3306:3306"
    networks:
      - default
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
  mlflow:
    restart: always
    build: ./mlflow
    image: mlflow_server
    container_name: mlflow_server
    depends_on:
      - mlflow-db
    ports:
      - "5050:5000"
    networks:
      - default
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mlflow-db:3306/${MYSQL_DATABASE} --default-artifact-root s3://mlflow/ --host 0.0.0.0



networks:
  default:
    driver: bridge

volumes:
  dbdata:
  minio_data:
